### ISSUE TITLE
Screen Color

### ISSUE THREAD

**Issue by GmrsKissimmee** [Fr4nkFletcher/NerdMiner_v2-Cheap-Yellow-Display#2]
Hello, my screen has different colors than the one in your photo

Blue, orange and white.

![IMG_20240620_193146](https://github.com/Fr4nkFletcher/NerdMiner_v2-Cheap-Yellow-Display/assets/155043316/1d29144e-8253-4e92-b183-6d81778b02c3)

**Comment by Fr4nkFletcher** [comment]
This happens on the two-usb model unfortunately

**Comment by GmrsKissimmee** [comment]
Thanks

**Comment by GmrsKissimmee** [comment]
If I want to make a change to the Wifi network, where can I do it? Since I don't see where to reconfigure it

**Comment by Fr4nkFletcher** [comment]
Reflash and start over I'm pretty sure. Here's the repo the flasher is based on if this helps https://github.com/BitMaker-hub/NerdMiner_v2
